name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


       # - name: Docker Login and Push
    #   run: |
    #       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #       docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:1.0 .
    #       docker push ${{ secrets.DOCKER_USERNAME }}/nginx:1.0
    

    # Uncomment the following lines if you want to work with AWS ECR
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1 # Replace with your AWS region, e.g., us-west-2


    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 939737198590.dkr.ecr.ap-southeast-1.amazonaws.com

    - name: Build and push Docker image to ECR
      run: |
        docker build -t nginx .
        docker tag nginx:latest 939737198590.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:1.0
        docker push 939737198590.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:1.0
